### PR TITLE
Fix release notes creation

### LINKED ISSUE #686: Create release from releases page
When I browse https://tinacms.org/docs/releases I can't create add a new release, I have to browse to https://tinacms.org/blog to do it.

When I add a new release page, then I get redirected to a 404.

**Demo**: https://www.loom.com/share/5d2bb44f8666429791c83ec2fdb30686

### PR DESCRIPTION
**Pull request by dwalkr**
fixes #686

### CODE REVIEW

File: pages/_app.tsx [hunk 1]
```diff
@@ -42,7 +44,12 @@ const MainLayout = ({ Component, pageProps }) => {
     },
   }
 
-  const cms = React.useMemo(() => new TinaCMS(tinaConfig), [])
+  const cms = React.useMemo(() => {
+    const cms = new TinaCMS(tinaConfig)
```
Comment (ncphillips) [inline pages/_app.tsx:48]: why not just list them in the config?

Comment (dwalkr) [reply pages/_app.tsx:48]: that would be way too easy
